#################################
## Super Linter GitHub Actions ##
#################################
name: Lint Code Base

#############################
## Start the job on a push ##
#############################
on: push

#################
## Set the Job ##
#################
jobs: 
  super-lint:
    # Name the Job #
    name: Lint Code
    # Set the agent to run on #
    runs-on: ubuntu-latest
    # Load all the steps #
    steps:
      # Checkout the code #
      - name: Checkout code base
        uses: actions/checkout@v4

      # Run linter against the code #
      - name: Run Super-Linter
        uses: github/super-linter@v5
